kind: LDAPSyncConfig
apiVersion: v1
url: ldap://dc1.example.com #LDAP URL | i.e. Active Directory Server address
bindDN: 'user@example.com' #Service Account with Domain Admins Group Membership
bindPassword: "password" #Password of Service Account
augmentedActiveDirectory:
  groupsQuery:
    baseDN: "OU=OCP,OU=Groups,DC=example,DC=com" #Distinguised Name of the OU under which target Group available
    scope: sub
    derefAliases: never
    pageSize: 0
  groupUIDAttribute: dn
  groupNameAttributes: [cn]
  usersQuery:
    baseDN: "OU=Users,DC=example,DC=com" #Distinguised Name of the OU under which target Group available
    scope: sub
    derefAliases: never
    filter: (objectclass=person)
    pageSize: 0
  userNameAttributes: [mail]
  groupMembershipAttributes: [memberOf]
